services:
  db:
    image: mariadb:11
    container_name: wistful-db
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -hlocalhost -u${DB_USER} -p${DB_PASSWORD} -e 'SELECT 1;' ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      wistful-net:
        ipv4_address: 172.12.0.2

  redis:
    image: redis:7
    container_name: wistful-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      wistful-net:
        ipv4_address: 172.12.0.3

  backend:
    build:
      context: ./DJANGO
      dockerfile: Dockerfile.prod
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    env_file:
      - ./DJANGO/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8000"
    command: uvicorn wistful.asgi:application --host 0.0.0.0 --port 8000 --workers 3
    volumes:
      - backend_static_volume:/app/staticfiles
      - backend_media_volume:/app/media
      - /srv/wistful/DJANGO_staticfiles:/app/staticfiles
      - /srv/wistful/DJANGO_media:/app/media
    networks:
      wistful-net:
        ipv4_address: 172.12.0.10

  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "stripe listen --api-key ${STRIPE_SECRET_KEY} --forward-to backend:8000/api/webhook/"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      backend:
        condition: service_started
    networks:
      - wistful-net

  frontend:
    build:
      context: ./REACT
      dockerfile: Dockerfile.prod
    env_file:
      - ./REACT/.env
    expose:
      - 80
    networks:
      wistful-net:
        ipv4_address: 172.12.0.11

volumes:
  mariadb_data:
  backend_static_volume:
  backend_media_volume:

networks:
  wistful-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.0.0/16
          gateway: 172.12.0.1