FROM node:20.18.1 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . ./
RUN chmod +x node_modules/.bin/vite && yarn build


FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

EXPOSE 80