# Generated by Django 5.0.11 on 2025-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='password',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
