# Generated by Django 5.0.11 on 2025-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_miembro_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='imagen_perfil',
            field=models.ImageField(default='perfil/default.jpg', upload_to='perfil/'),
        ),
    ]
