# Generated by Django 5.0.11 on 2025-04-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_miembro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.miembro'),
        ),
    ]
