# Generated by Django 5.0.11 on 2025-04-25 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_meet_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combatiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='combatientes/')),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('salud', models.PositiveIntegerField(default=100)),
                ('daño', models.PositiveIntegerField(default=10)),
                ('habilidad_1', models.CharField(max_length=50)),
                ('habilidad_2', models.CharField(max_length=50)),
                ('habilidad_3', models.CharField(max_length=50)),
                ('habilidad_4', models.CharField(max_length=50)),
                ('trofeos', models.PositiveIntegerField(default=0)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combatiente', to='users.miembro')),
            ],
        ),
    ]
