# Generated by Django 5.0.11 on 2025-04-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_combatiente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combatiente',
            old_name='daño',
            new_name='damage',
        ),
    ]
