# Generated by Django 5.0.11 on 2025-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_daño_combatiente_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatiente',
            name='experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
